extends Node

signal character_dead()
signal mission_success()
signal mission_start()
signal mission_end()
signal spawn_locations_updated()
signal enemies_updated()
signal character_spawned()
signal selected_card_updated()
signal character_path_updated()
signal moves_available_updated()
signal character_location_updated()
signal character_attack(enemy, attack)
signal character_attack_done()
signal character_health_update()
signal charcter_hurt(enemy_location)
signal hand_updated()
signal discard_updated()
